### ISSUE TITLE
Group Members 

### ISSUE THREAD

**Issue by sentayhu19** [sentayhu19/Catalog-of-my-things#20]
Project Link : https://github.com/sentayhu19/Catalog-of-my-things/projects/1
Group Members 

- @sangwa7 
- @sentayhu19 
- @LionRouge1 
- @moise-mulungu

**Comment by keroloussamy** [comment]
Hi Team, 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project, that doesn't have the project link, Kindly add the link for your project.

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

**Comment by Lameck1** [comment]
Hi, Team,

You've done well implementing your Kanban board 👏🏼. 

### Highlights:
- You've properly assigned yourselves tasks ✔️
- Task distribution is fair. ✔️

All the best with the next project.

You are free to merge this branch :shipit:
Congratulations! 🎉 

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
**Please, remember to tag me in your question so I can receive the notification.**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
